lib/super_perfundo_web/router.ex
defmodule SuperPerfundoWeb.Router do
  use SuperPerfundoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SuperPerfundoWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  if Mix.env() == :dev do
    forward "/emails", Bamboo.SentEmailViewerPlug
  end

  scope "/", SuperPerfundoWeb do
    pipe_through :browser

    get "/", BlogController, :index
    get "/about", BlogController, :about
    get "/articles/:id", BlogController, :show
    get "/drafts/:id", BlogController, :show_draft

    post "/subscribe", SubscriptionController, :create
    get "/unsubscribe/:email", SubscriptionController, :edit
    delete "/unsubscribe/:email", SubscriptionController, :destroy

    live "/quarto", QuartoLive
  end
end

lib/super_perfundo_web/views/layout_view.ex
defmodule SuperPerfundoWeb.LayoutView do
  use SuperPerfundoWeb, :view

  def og_description(%{post: post}), do: post.description
  def og_description(_), do: ""

  def og_title(%{post: post}), do: post.title
  def og_title(_), do: ""

  def og_image(%{post: post, conn: conn}), do: Routes.static_url(conn, "/images/#{post.image}")
  def og_image(_), do: ""

  def post_id(%{post: post}), do: post.id
  def post_id(_), do: ""
end

lib/super_perfundo_web/templates/layout/app.html.eex
<main role="main">
  <%= @inner_content %>
</main>

lib/super_perfundo_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <meta property="og:title" content="<%= og_title(assigns) %>">
    <meta property="og:description" content="<%= og_description(assigns) %>">
    <meta property="og:image" content="<%= og_image(assigns) %>">
    <meta property="og:url" content="<%= Routes.blog_url(@conn, :show, post_id(assigns)) %>">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="en_US">
    <meta property="og:site_name" content="SuperPerfundo.Tech">

    <title><%= assigns[:page_title] || "SuperPerfundo.Tech" %></title>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2:wght@600&family=Spartan:wght@400;800&family=Inter:wght@300;400;700&family=Source+Code+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <div id="header-container">
        <div id="blog-title">SuperPerfundo.Tech</div>
        <nav>
          <%= link("ARTICLES", to: "/") %>
          <%= link("QUARTO", to: "/quarto") %>
          <%= link("ABOUT", to: "/about") %>
          <div id="responsive-nav">
            <input type="checkbox" />
            <div id="burger">
              <span></span>
              <span></span>
              <span></span>
            </div>
            <ul>
              <a href="/"><li>ARTICLES</li></a>
              <a href="/quarto"><li>QUARTO</li></a>
              <a href="/about"><li>ABOUT</li></a>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <%= @inner_content %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>